# ===============================================================================
# _  _
# __ _| | __ _ _ __ ___  ___ _ __(_) __ _ _ __ ___  ___ _ __ ___
# / _` | |/ _` | '_ \ / _ \| '__| |/ _` | \ \/ / | | |_ /
# | (_| | | (_| | | | | | (_) | |  | | (_| | >  <| |_| |/ /
# \__,_|_|\__,_|_| |_|\___/|_|  |_|\__,_/_/\_\\__,_/___|
# |___/
# ===============================================================================
#
# IMPORTANTE:
#
# Modifique essas configurações APENAS se você tiver certeza do que está fazendo.
#
# ===============================================================================
#
# REQUISITOS NECESSÁRIOS:
#
# É extremamente importante seguir os seguintes passos:
#
# 1. Crie o arquivo necessário para armazenar os certificados SSL:
# $ touch acme.json
#
# 2. Defina as permissões corretas para o arquivo `acme.json`:
# $ sudo chmod 600 acme.json
#
# 3. Procure a linha abaixo e substitua pelo seu e-mail:
# - `--certificatesresolvers.leresolver.acme.email=seuemail@example.com
#
# Só então execute o comando:
# $ docker compose -f traefik-docker-compose.yml up -d
#
# ===============================================================================

services:
  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: always
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker"
      - "--log.level=ERROR"
      - "--certificatesresolvers.leresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=seuemail@example.com"
      - "--certificatesresolvers.leresolver.acme.storage=/root/myvps/acme.json"
      - "--certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - traefik

networks:
  traefik:
    name: traefik 